import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Release Ready",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}